[package]
name = "circuit"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
polynomial.workspace = true
ark-ff.workspace = true
ark-test-curves.workspace = true
